309: Put a regular text hyperlink under the widget that performs the desired action
dambaev/op-energy pull request #318
Opened 2023-01-27 12:03 UTC by Natsvora

309: Added click events instead of hyperlinks on the action widget

2023-01-29 10:12 UTC, dambaev requested changes

2023-01-29 10:12 UTC, dambaev commented on frontend/src/app/oe/components/base-box-hor/base-box-hor.component.ts
>    toHHMMSS(secs) {
I see basebox.component.ts contains the same function. I suggest to refactor it into reusable one.

2023-01-31 01:31 UTC, dambaev commented
my suggestion was about `toHHMMSS` function, not about navigation

2023-01-31 01:34 UTC, dambaev requested changes, later dismissed
my suggestion was about `toHHMMSS` function, not about navigation

2023-02-03 09:40 UTC, girish-velas commented
I am fine with the code - but would recommend creating components where same code exists to keep everything lean

2023-02-03 09:41 UTC, girish-velas approved these changes
try to create common components in a follow up PR to make code better

2023-02-03 09:43 UTC, merged